config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

 
  resources :users , only: [:edit, :show, :update]
  resources :date_records, only: [:edit, :update]
 

  shallow do
    resources :students, only: [:show] do
       resources :texts, only: [:new,:create]
    end
  end

  shallow do 
    resources :cohorts, except: [:destroy, :show] do
      resources :students, only: [:new, :create]
      resources :date_records, only: [:index] 
    end
  end

  post '/' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'cohorts/:id/students' => 'cohorts#show'
  get 'cohorts/:id/students/date_records/new' => 'date_records#new'
  post 'cohorts/:id/students/date_records' => 'date_records#create'
  post '/texts' => 'texts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AttendanceTrackerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= yield :css %>
</head>
<body>
	<header>
		<% if @user%> 
		<div>
			<nav class="grid-full">
				<ul class="nav-links">
					<li class="grid-5-8"><%= @user.first_name %> <%= @user.last_name %></li>
					<li class="grid-1-8"><a href="/users/<%=@user.id%>">Profile</a></li>
					<li class="grid-1-8"><%= link_to "Cohorts", cohorts_path %></li>
					<li class="grid-1-8"><%= link_to "Log Out", logout_path %></li>
				</ul>
			</nav>
		</div>
		<%end%>
	</header>
<div class="content">
	<%= yield %>
</div>
</body>
</html>